import {
  type Client,
  type ClientDashboardSummary,
  type CommentAnalysis,
  type DashboardKpi,
  type EmotionScore,
  type Post,
  type SocialAccount,
} from "@/types/social";

export const MOCK_DASHBOARD_KPIS: DashboardKpi[] = [
  {
    id: "total-clients",
    label: "Total Clientes",
    value: "142",
    delta: "+8%",
    context: "vs. mes anterior",
  },
  {
    id: "total-posts",
    label: "Publicaciones",
    value: "1,540",
    delta: "+12%",
    context: "últimos 30 días",
  },
  {
    id: "total-comments",
    label: "Comentarios",
    value: "45,200",
    delta: "+4%",
    context: "últimos 30 días",
  },
  {
    id: "analyzed-comments",
    label: "Analizados",
    value: "36,700",
    delta: "+18%",
    context: "procesados por IA",
  },
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: "techcorp",
    name: "TechCorp Inc.",
    shortName: "TC",
    industry: "Tecnología",
    description: "SaaS B2B para automatización comercial.",
    status: "Activo",
    connected: true,
    avatarColor: "#0f766e",
  },
  {
    id: "elbuen-sabor",
    name: "Restaurante El Buen Sabor",
    shortName: "RBS",
    industry: "Gastronomía",
    description: "Restaurante con menú estacional y delivery propio.",
    status: "Activo",
    connected: true,
    avatarColor: "#b45309",
  },
  {
    id: "moda-viva",
    name: "Moda Viva",
    shortName: "MV",
    industry: "Retail",
    description: "Marca de ropa urbana con ecommerce en crecimiento.",
    status: "Pendiente",
    connected: false,
    avatarColor: "#7c3aed",
  },
  {
    id: "biofit-bol",
    name: "BioFit Bolivia",
    shortName: "BF",
    industry: "Salud y bienestar",
    description: "Suplementos y asesorías para estilo de vida saludable.",
    status: "Sin cuenta",
    connected: false,
    avatarColor: "#2563eb",
  },
];

export const MOCK_TRENDING_EMOTIONS: EmotionScore[] = [
  { emotion: "Joy", count: 1250, percentage: 41 },
  { emotion: "Love", count: 810, percentage: 27 },
  { emotion: "Surprise", count: 420, percentage: 14 },
  { emotion: "Anger", count: 300, percentage: 10 },
  { emotion: "Sadness", count: 270, percentage: 8 },
];

export const MOCK_ACCOUNTS: SocialAccount[] = [
  {
    id: "acc-rbs-ig",
    clientId: "elbuen-sabor",
    platform: "Instagram Business",
    handle: "@elbuen_sabor",
    igBusinessId: "17841400000000000",
    facebookPage: "El Buen Sabor Oficial",
    scopes: ["instagram_basic", "instagram_manage_comments", "pages_show_list"],
    status: "Conectado",
    lastSync: "hace 12 min",
  },
  {
    id: "acc-tc-ig",
    clientId: "techcorp",
    platform: "Instagram Business",
    handle: "@techcorp.latam",
    igBusinessId: "17841400000000091",
    facebookPage: "TechCorp LATAM",
    scopes: ["instagram_basic", "instagram_manage_comments"],
    status: "Conectado",
    lastSync: "hace 26 min",
  },
  {
    id: "acc-mv-ig",
    clientId: "moda-viva",
    platform: "Instagram Business",
    handle: "@modaviva.bo",
    igBusinessId: "-",
    facebookPage: "-",
    scopes: [],
    status: "Pendiente",
    lastSync: "sin sincronización",
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "post-rbs-01",
    clientId: "elbuen-sabor",
    caption: "Menú de verano con ingredientes frescos.",
    publishedAt: "12 de abril, 2025",
    imageHint: "Pasta artesanal en plato rústico",
    likes: 423,
    commentsCount: 85,
    analyzedComments: 72,
  },
  {
    id: "post-rbs-02",
    clientId: "elbuen-sabor",
    caption: "Combo familiar para fin de semana.",
    publishedAt: "19 de abril, 2025",
    imageHint: "Mesa con platos para compartir",
    likes: 371,
    commentsCount: 64,
    analyzedComments: 41,
  },
  {
    id: "post-tc-01",
    clientId: "techcorp",
    caption: "Lanzamos dashboard de ventas en tiempo real.",
    publishedAt: "03 de mayo, 2025",
    imageHint: "Pantalla analítica con gráficas",
    likes: 250,
    commentsCount: 39,
    analyzedComments: 35,
  },
  {
    id: "post-tc-02",
    clientId: "techcorp",
    caption: "Webinar gratuito sobre automatización comercial.",
    publishedAt: "10 de mayo, 2025",
    imageHint: "Ponente en conferencia virtual",
    likes: 182,
    commentsCount: 24,
    analyzedComments: 18,
  },
  {
    id: "post-mv-01",
    clientId: "moda-viva",
    caption: "Nueva colección cápsula otoño 2025.",
    publishedAt: "29 de marzo, 2025",
    imageHint: "Modelo con prendas urbanas",
    likes: 498,
    commentsCount: 111,
    analyzedComments: 0,
  },
];

export const MOCK_COMMENT_ANALYSIS: CommentAnalysis[] = [
  {
    id: "c-rbs-1",
    postId: "post-rbs-01",
    username: "@maria.l",
    text: "La pasta estaba deliciosa, volvería 100 veces.",
    likes: 12,
    createdAt: "hace 2h",
    sentiment: "Positivo",
    emotion: "Joy",
    confidence: 0.98,
    status: "analyzed",
  },
  {
    id: "c-rbs-2",
    postId: "post-rbs-01",
    username: "@carlos.r",
    text: "El servicio fue excelente, muy rápido y amable.",
    likes: 7,
    createdAt: "hace 5h",
    sentiment: "Positivo",
    emotion: "Love",
    confidence: 0.94,
    status: "analyzed",
  },
  {
    id: "c-rbs-3",
    postId: "post-rbs-01",
    username: "@andrea.m",
    text: "El precio me pareció alto para lo que ofrecen.",
    likes: 2,
    createdAt: "hace 1d",
    sentiment: "Negativo",
    emotion: "Anger",
    confidence: 0.87,
    status: "analyzed",
  },
  {
    id: "c-rbs-4",
    postId: "post-rbs-01",
    username: "@pedro.g",
    text: "¿Tienen opciones vegetarianas para mi próxima visita?",
    likes: 0,
    createdAt: "hace 2d",
    sentiment: "Neutral",
    emotion: "Surprise",
    confidence: 0.79,
    status: "analyzed",
  },
  {
    id: "c-rbs-5",
    postId: "post-rbs-01",
    username: "@juan.t",
    text: "¿Cuál es el horario del fin de semana?",
    likes: 1,
    createdAt: "hace 4d",
    sentiment: "Neutral",
    emotion: "Surprise",
    confidence: null,
    status: "pending",
  },
  {
    id: "c-rbs-6",
    postId: "post-rbs-02",
    username: "@laura.b",
    text: "Excelente promoción para ir con toda la familia.",
    likes: 4,
    createdAt: "hace 7h",
    sentiment: "Positivo",
    emotion: "Joy",
    confidence: 0.9,
    status: "analyzed",
  },
  {
    id: "c-rbs-7",
    postId: "post-rbs-02",
    username: "@dani.p",
    text: "La porción vino más pequeña de lo esperado.",
    likes: 2,
    createdAt: "hace 11h",
    sentiment: "Negativo",
    emotion: "Sadness",
    confidence: 0.73,
    status: "analyzed",
  },
  {
    id: "c-tc-1",
    postId: "post-tc-01",
    username: "@ana.pm",
    text: "La nueva vista de métricas está buenísima.",
    likes: 8,
    createdAt: "hace 3h",
    sentiment: "Positivo",
    emotion: "Joy",
    confidence: 0.93,
    status: "analyzed",
  },
  {
    id: "c-tc-2",
    postId: "post-tc-01",
    username: "@leo.dev",
    text: "No me cargó bien en móvil, revisen por favor.",
    likes: 3,
    createdAt: "hace 1d",
    sentiment: "Negativo",
    emotion: "Anger",
    confidence: 0.81,
    status: "analyzed",
  },
  {
    id: "c-tc-3",
    postId: "post-tc-02",
    username: "@lu.ma",
    text: "¿Habrá grabación del webinar?",
    likes: 0,
    createdAt: "hace 1d",
    sentiment: "Neutral",
    emotion: "Surprise",
    confidence: null,
    status: "pending",
  },
  {
    id: "c-mv-1",
    postId: "post-mv-01",
    username: "@carla.style",
    text: "Está increíble la nueva colección, amé los colores.",
    likes: 15,
    createdAt: "hace 2h",
    sentiment: "Positivo",
    emotion: "Love",
    confidence: null,
    status: "pending",
  },
  {
    id: "c-mv-2",
    postId: "post-mv-01",
    username: "@mike.urban",
    text: "Esperaba más tallas disponibles.",
    likes: 5,
    createdAt: "hace 10h",
    sentiment: "Negativo",
    emotion: "Sadness",
    confidence: null,
    status: "pending",
  },
];

export const MOCK_CLIENT_SUMMARY: Record<string, ClientDashboardSummary> = {
  "elbuen-sabor": {
    client: MOCK_CLIENTS[1],
    kpis: [
      { id: "posts", label: "Publicaciones", value: "24", delta: "+3", context: "último mes" },
      { id: "comments", label: "Comentarios", value: "1,842", delta: "+12%", context: "último mes" },
      { id: "engagement", label: "Engagement", value: "8.2%", delta: "+0.5", context: "promedio" },
      { id: "sentiment", label: "Positivos", value: "72%", delta: "+4%", context: "comentarios" },
    ],
    emotionDistribution: [
      { emotion: "Joy", count: 426, percentage: 47 },
      { emotion: "Love", count: 202, percentage: 22 },
      { emotion: "Surprise", count: 129, percentage: 14 },
      { emotion: "Anger", count: 88, percentage: 10 },
      { emotion: "Sadness", count: 65, percentage: 7 },
    ],
    topPosts: MOCK_POSTS.filter((post) => post.clientId === "elbuen-sabor"),
  },
  techcorp: {
    client: MOCK_CLIENTS[0],
    kpis: [
      { id: "posts", label: "Publicaciones", value: "16", delta: "+2", context: "último mes" },
      { id: "comments", label: "Comentarios", value: "492", delta: "+6%", context: "último mes" },
      { id: "engagement", label: "Engagement", value: "5.9%", delta: "+0.4", context: "promedio" },
      { id: "sentiment", label: "Positivos", value: "68%", delta: "+2%", context: "comentarios" },
    ],
    emotionDistribution: [
      { emotion: "Joy", count: 151, percentage: 38 },
      { emotion: "Love", count: 109, percentage: 27 },
      { emotion: "Surprise", count: 77, percentage: 19 },
      { emotion: "Anger", count: 43, percentage: 11 },
      { emotion: "Sadness", count: 20, percentage: 5 },
    ],
    topPosts: MOCK_POSTS.filter((post) => post.clientId === "techcorp"),
  },
};

export function deepClone<T>(input: T): T {
  return JSON.parse(JSON.stringify(input)) as T;
}


